namespace DepoProjem
{
    partial class UrunEkle
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UrunEkle));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.exit = new System.Windows.Forms.Label();
            this.txtUrunAdı = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtUrunTedarikcisi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtUrunBırımFıyatı = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtUrunID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtUrunAgırlıgı = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtUrunMevcutStokMiktari = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtUrunBarkodSeriNo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtUrunKategorisi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGroupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // exit
            // 
            this.exit.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.exit.AutoSize = true;
            this.exit.Cursor = System.Windows.Forms.Cursors.Hand;
            this.exit.Font = new System.Drawing.Font("Tahoma", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.exit.ForeColor = System.Drawing.Color.White;
            this.exit.Location = new System.Drawing.Point(1121, -1);
            this.exit.Name = "exit";
            this.exit.Size = new System.Drawing.Size(17, 18);
            this.exit.TabIndex = 17;
            this.exit.Text = "X";
            this.exit.Click += new System.EventHandler(this.exit_Click);
            // 
            // txtUrunAdı
            // 
            this.txtUrunAdı.AcceptsReturn = false;
            this.txtUrunAdı.AcceptsTab = false;
            this.txtUrunAdı.AnimationSpeed = 200;
            this.txtUrunAdı.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUrunAdı.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUrunAdı.BackColor = System.Drawing.Color.Transparent;
            this.txtUrunAdı.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUrunAdı.BackgroundImage")));
            this.txtUrunAdı.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUrunAdı.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUrunAdı.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUrunAdı.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUrunAdı.BorderRadius = 20;
            this.txtUrunAdı.BorderThickness = 1;
            this.txtUrunAdı.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUrunAdı.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunAdı.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtUrunAdı.DefaultText = "";
            this.txtUrunAdı.FillColor = System.Drawing.Color.White;
            this.txtUrunAdı.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtUrunAdı.HideSelection = true;
            this.txtUrunAdı.IconLeft = null;
            this.txtUrunAdı.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunAdı.IconPadding = 10;
            this.txtUrunAdı.IconRight = null;
            this.txtUrunAdı.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunAdı.Lines = new string[0];
            this.txtUrunAdı.Location = new System.Drawing.Point(114, 49);
            this.txtUrunAdı.MaxLength = 32767;
            this.txtUrunAdı.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUrunAdı.Modified = false;
            this.txtUrunAdı.Multiline = false;
            this.txtUrunAdı.Name = "txtUrunAdı";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunAdı.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUrunAdı.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunAdı.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunAdı.OnIdleState = stateProperties4;
            this.txtUrunAdı.Padding = new System.Windows.Forms.Padding(3);
            this.txtUrunAdı.PasswordChar = '\0';
            this.txtUrunAdı.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtUrunAdı.PlaceholderText = "Ürüne Ait Ad";
            this.txtUrunAdı.ReadOnly = false;
            this.txtUrunAdı.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUrunAdı.SelectedText = "";
            this.txtUrunAdı.SelectionLength = 0;
            this.txtUrunAdı.SelectionStart = 0;
            this.txtUrunAdı.ShortcutsEnabled = true;
            this.txtUrunAdı.Size = new System.Drawing.Size(260, 37);
            this.txtUrunAdı.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUrunAdı.TabIndex = 8;
            this.txtUrunAdı.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUrunAdı.TextMarginBottom = 0;
            this.txtUrunAdı.TextMarginLeft = 3;
            this.txtUrunAdı.TextMarginTop = 0;
            this.txtUrunAdı.TextPlaceholder = "Ürüne Ait Ad";
            this.txtUrunAdı.UseSystemPasswordChar = false;
            this.txtUrunAdı.WordWrap = true;
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.DimGray;
            this.bunifuGroupBox2.BorderRadius = 20;
            this.bunifuGroupBox2.BorderThickness = 1;
            this.bunifuGroupBox2.Controls.Add(this.bunifuButton1);
            this.bunifuGroupBox2.Controls.Add(this.txtUrunAdı);
            this.bunifuGroupBox2.Controls.Add(this.txtUrunTedarikcisi);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel8);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel2);
            this.bunifuGroupBox2.Controls.Add(this.txtUrunBırımFıyatı);
            this.bunifuGroupBox2.Controls.Add(this.txtUrunID);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel7);
            this.bunifuGroupBox2.Controls.Add(this.txtUrunAgırlıgı);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel1);
            this.bunifuGroupBox2.Controls.Add(this.txtUrunMevcutStokMiktari);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel6);
            this.bunifuGroupBox2.Controls.Add(this.txtUrunBarkodSeriNo);
            this.bunifuGroupBox2.Controls.Add(this.txtUrunKategorisi);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel3);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel5);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel4);
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.bunifuGroupBox2.ForeColor = System.Drawing.Color.White;
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(97, 56);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(1004, 519);
            this.bunifuGroupBox2.TabIndex = 19;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "Ürün Bilgileri";
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.SpringGreen;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "EKLE";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges1;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.IdleBorderRadius = 35;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.SpringGreen;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(425, 432);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 35;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 35;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.BorderRadius = 35;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.SpringGreen;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 35;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(150, 58);
            this.bunifuButton1.TabIndex = 16;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // txtUrunTedarikcisi
            // 
            this.txtUrunTedarikcisi.AcceptsReturn = false;
            this.txtUrunTedarikcisi.AcceptsTab = false;
            this.txtUrunTedarikcisi.AnimationSpeed = 200;
            this.txtUrunTedarikcisi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUrunTedarikcisi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUrunTedarikcisi.BackColor = System.Drawing.Color.Transparent;
            this.txtUrunTedarikcisi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUrunTedarikcisi.BackgroundImage")));
            this.txtUrunTedarikcisi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUrunTedarikcisi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUrunTedarikcisi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUrunTedarikcisi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUrunTedarikcisi.BorderRadius = 20;
            this.txtUrunTedarikcisi.BorderThickness = 1;
            this.txtUrunTedarikcisi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUrunTedarikcisi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunTedarikcisi.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtUrunTedarikcisi.DefaultText = "";
            this.txtUrunTedarikcisi.FillColor = System.Drawing.Color.White;
            this.txtUrunTedarikcisi.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtUrunTedarikcisi.HideSelection = true;
            this.txtUrunTedarikcisi.IconLeft = null;
            this.txtUrunTedarikcisi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunTedarikcisi.IconPadding = 10;
            this.txtUrunTedarikcisi.IconRight = null;
            this.txtUrunTedarikcisi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunTedarikcisi.Lines = new string[0];
            this.txtUrunTedarikcisi.Location = new System.Drawing.Point(657, 366);
            this.txtUrunTedarikcisi.MaxLength = 32767;
            this.txtUrunTedarikcisi.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUrunTedarikcisi.Modified = false;
            this.txtUrunTedarikcisi.Multiline = false;
            this.txtUrunTedarikcisi.Name = "txtUrunTedarikcisi";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunTedarikcisi.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUrunTedarikcisi.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunTedarikcisi.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunTedarikcisi.OnIdleState = stateProperties8;
            this.txtUrunTedarikcisi.Padding = new System.Windows.Forms.Padding(3);
            this.txtUrunTedarikcisi.PasswordChar = '\0';
            this.txtUrunTedarikcisi.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtUrunTedarikcisi.PlaceholderText = "Yoksa Boş Bırakın";
            this.txtUrunTedarikcisi.ReadOnly = false;
            this.txtUrunTedarikcisi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUrunTedarikcisi.SelectedText = "";
            this.txtUrunTedarikcisi.SelectionLength = 0;
            this.txtUrunTedarikcisi.SelectionStart = 0;
            this.txtUrunTedarikcisi.ShortcutsEnabled = true;
            this.txtUrunTedarikcisi.Size = new System.Drawing.Size(260, 37);
            this.txtUrunTedarikcisi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUrunTedarikcisi.TabIndex = 15;
            this.txtUrunTedarikcisi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUrunTedarikcisi.TextMarginBottom = 0;
            this.txtUrunTedarikcisi.TextMarginLeft = 3;
            this.txtUrunTedarikcisi.TextMarginTop = 0;
            this.txtUrunTedarikcisi.TextPlaceholder = "Yoksa Boş Bırakın";
            this.txtUrunTedarikcisi.UseSystemPasswordChar = false;
            this.txtUrunTedarikcisi.WordWrap = true;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Calibri", 12F);
            this.bunifuLabel8.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel8.Location = new System.Drawing.Point(507, 373);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(109, 19);
            this.bunifuLabel8.TabIndex = 7;
            this.bunifuLabel8.Text = "Ürün Tedarikçisi:";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Calibri", 12F);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(24, 58);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(60, 19);
            this.bunifuLabel2.TabIndex = 1;
            this.bunifuLabel2.Text = "Ürün Adı:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtUrunBırımFıyatı
            // 
            this.txtUrunBırımFıyatı.AcceptsReturn = false;
            this.txtUrunBırımFıyatı.AcceptsTab = false;
            this.txtUrunBırımFıyatı.AnimationSpeed = 200;
            this.txtUrunBırımFıyatı.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUrunBırımFıyatı.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUrunBırımFıyatı.BackColor = System.Drawing.Color.Transparent;
            this.txtUrunBırımFıyatı.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUrunBırımFıyatı.BackgroundImage")));
            this.txtUrunBırımFıyatı.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUrunBırımFıyatı.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUrunBırımFıyatı.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUrunBırımFıyatı.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUrunBırımFıyatı.BorderRadius = 20;
            this.txtUrunBırımFıyatı.BorderThickness = 1;
            this.txtUrunBırımFıyatı.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUrunBırımFıyatı.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunBırımFıyatı.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtUrunBırımFıyatı.DefaultText = "";
            this.txtUrunBırımFıyatı.FillColor = System.Drawing.Color.White;
            this.txtUrunBırımFıyatı.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtUrunBırımFıyatı.HideSelection = true;
            this.txtUrunBırımFıyatı.IconLeft = null;
            this.txtUrunBırımFıyatı.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunBırımFıyatı.IconPadding = 10;
            this.txtUrunBırımFıyatı.IconRight = null;
            this.txtUrunBırımFıyatı.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunBırımFıyatı.Lines = new string[0];
            this.txtUrunBırımFıyatı.Location = new System.Drawing.Point(172, 366);
            this.txtUrunBırımFıyatı.MaxLength = 32767;
            this.txtUrunBırımFıyatı.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUrunBırımFıyatı.Modified = false;
            this.txtUrunBırımFıyatı.Multiline = false;
            this.txtUrunBırımFıyatı.Name = "txtUrunBırımFıyatı";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunBırımFıyatı.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUrunBırımFıyatı.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunBırımFıyatı.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunBırımFıyatı.OnIdleState = stateProperties12;
            this.txtUrunBırımFıyatı.Padding = new System.Windows.Forms.Padding(3);
            this.txtUrunBırımFıyatı.PasswordChar = '\0';
            this.txtUrunBırımFıyatı.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtUrunBırımFıyatı.PlaceholderText = "Bir Ürünün Fiyatı";
            this.txtUrunBırımFıyatı.ReadOnly = false;
            this.txtUrunBırımFıyatı.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUrunBırımFıyatı.SelectedText = "";
            this.txtUrunBırımFıyatı.SelectionLength = 0;
            this.txtUrunBırımFıyatı.SelectionStart = 0;
            this.txtUrunBırımFıyatı.ShortcutsEnabled = true;
            this.txtUrunBırımFıyatı.Size = new System.Drawing.Size(260, 37);
            this.txtUrunBırımFıyatı.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUrunBırımFıyatı.TabIndex = 14;
            this.txtUrunBırımFıyatı.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUrunBırımFıyatı.TextMarginBottom = 0;
            this.txtUrunBırımFıyatı.TextMarginLeft = 3;
            this.txtUrunBırımFıyatı.TextMarginTop = 0;
            this.txtUrunBırımFıyatı.TextPlaceholder = "Bir Ürünün Fiyatı";
            this.txtUrunBırımFıyatı.UseSystemPasswordChar = false;
            this.txtUrunBırımFıyatı.WordWrap = true;
            this.txtUrunBırımFıyatı.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtUrunBırımFıyatı_KeyPress);
            // 
            // txtUrunID
            // 
            this.txtUrunID.AcceptsReturn = false;
            this.txtUrunID.AcceptsTab = false;
            this.txtUrunID.AnimationSpeed = 200;
            this.txtUrunID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUrunID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUrunID.BackColor = System.Drawing.Color.Transparent;
            this.txtUrunID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUrunID.BackgroundImage")));
            this.txtUrunID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUrunID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUrunID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUrunID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUrunID.BorderRadius = 20;
            this.txtUrunID.BorderThickness = 1;
            this.txtUrunID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUrunID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtUrunID.DefaultText = "";
            this.txtUrunID.FillColor = System.Drawing.Color.White;
            this.txtUrunID.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtUrunID.HideSelection = true;
            this.txtUrunID.IconLeft = null;
            this.txtUrunID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunID.IconPadding = 10;
            this.txtUrunID.IconRight = null;
            this.txtUrunID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunID.Lines = new string[0];
            this.txtUrunID.Location = new System.Drawing.Point(636, 49);
            this.txtUrunID.MaxLength = 32767;
            this.txtUrunID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUrunID.Modified = false;
            this.txtUrunID.Multiline = false;
            this.txtUrunID.Name = "txtUrunID";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunID.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUrunID.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunID.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunID.OnIdleState = stateProperties16;
            this.txtUrunID.Padding = new System.Windows.Forms.Padding(3);
            this.txtUrunID.PasswordChar = '\0';
            this.txtUrunID.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtUrunID.PlaceholderText = "Ürüne Vermek İstediğiniz Numara";
            this.txtUrunID.ReadOnly = false;
            this.txtUrunID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUrunID.SelectedText = "";
            this.txtUrunID.SelectionLength = 0;
            this.txtUrunID.SelectionStart = 0;
            this.txtUrunID.ShortcutsEnabled = true;
            this.txtUrunID.Size = new System.Drawing.Size(260, 37);
            this.txtUrunID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUrunID.TabIndex = 9;
            this.txtUrunID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUrunID.TextMarginBottom = 0;
            this.txtUrunID.TextMarginLeft = 3;
            this.txtUrunID.TextMarginTop = 0;
            this.txtUrunID.TextPlaceholder = "Ürüne Vermek İstediğiniz Numara";
            this.txtUrunID.UseSystemPasswordChar = false;
            this.txtUrunID.WordWrap = true;
            this.txtUrunID.TextChanged += new System.EventHandler(this.txtUrunID_TextChanged);
            this.txtUrunID.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtUrunID_KeyPress);
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Calibri", 12F);
            this.bunifuLabel7.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel7.Location = new System.Drawing.Point(22, 373);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(112, 19);
            this.bunifuLabel7.TabIndex = 6;
            this.bunifuLabel7.Text = "Ürün Birim Fiyatı:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtUrunAgırlıgı
            // 
            this.txtUrunAgırlıgı.AcceptsReturn = false;
            this.txtUrunAgırlıgı.AcceptsTab = false;
            this.txtUrunAgırlıgı.AnimationSpeed = 200;
            this.txtUrunAgırlıgı.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUrunAgırlıgı.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUrunAgırlıgı.BackColor = System.Drawing.Color.Transparent;
            this.txtUrunAgırlıgı.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUrunAgırlıgı.BackgroundImage")));
            this.txtUrunAgırlıgı.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUrunAgırlıgı.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUrunAgırlıgı.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUrunAgırlıgı.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUrunAgırlıgı.BorderRadius = 20;
            this.txtUrunAgırlıgı.BorderThickness = 1;
            this.txtUrunAgırlıgı.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUrunAgırlıgı.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunAgırlıgı.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtUrunAgırlıgı.DefaultText = "";
            this.txtUrunAgırlıgı.FillColor = System.Drawing.Color.White;
            this.txtUrunAgırlıgı.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtUrunAgırlıgı.HideSelection = true;
            this.txtUrunAgırlıgı.IconLeft = null;
            this.txtUrunAgırlıgı.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunAgırlıgı.IconPadding = 10;
            this.txtUrunAgırlıgı.IconRight = null;
            this.txtUrunAgırlıgı.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunAgırlıgı.Lines = new string[0];
            this.txtUrunAgırlıgı.Location = new System.Drawing.Point(657, 269);
            this.txtUrunAgırlıgı.MaxLength = 32767;
            this.txtUrunAgırlıgı.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUrunAgırlıgı.Modified = false;
            this.txtUrunAgırlıgı.Multiline = false;
            this.txtUrunAgırlıgı.Name = "txtUrunAgırlıgı";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunAgırlıgı.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUrunAgırlıgı.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunAgırlıgı.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunAgırlıgı.OnIdleState = stateProperties20;
            this.txtUrunAgırlıgı.Padding = new System.Windows.Forms.Padding(3);
            this.txtUrunAgırlıgı.PasswordChar = '\0';
            this.txtUrunAgırlıgı.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtUrunAgırlıgı.PlaceholderText = "Kilogram Cinsinden(örn:500)";
            this.txtUrunAgırlıgı.ReadOnly = false;
            this.txtUrunAgırlıgı.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUrunAgırlıgı.SelectedText = "";
            this.txtUrunAgırlıgı.SelectionLength = 0;
            this.txtUrunAgırlıgı.SelectionStart = 0;
            this.txtUrunAgırlıgı.ShortcutsEnabled = true;
            this.txtUrunAgırlıgı.Size = new System.Drawing.Size(260, 37);
            this.txtUrunAgırlıgı.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUrunAgırlıgı.TabIndex = 13;
            this.txtUrunAgırlıgı.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUrunAgırlıgı.TextMarginBottom = 0;
            this.txtUrunAgırlıgı.TextMarginLeft = 3;
            this.txtUrunAgırlıgı.TextMarginTop = 0;
            this.txtUrunAgırlıgı.TextPlaceholder = "Kilogram Cinsinden(örn:500)";
            this.txtUrunAgırlıgı.UseSystemPasswordChar = false;
            this.txtUrunAgırlıgı.WordWrap = true;
            this.txtUrunAgırlıgı.TextChanged += new System.EventHandler(this.txtUrunAgırlıgı_TextChanged);
            this.txtUrunAgırlıgı.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtUrunAgırlıgı_KeyPress);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Calibri", 12F);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(500, 60);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(101, 19);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Ürün Numarası:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtUrunMevcutStokMiktari
            // 
            this.txtUrunMevcutStokMiktari.AcceptsReturn = false;
            this.txtUrunMevcutStokMiktari.AcceptsTab = false;
            this.txtUrunMevcutStokMiktari.AnimationSpeed = 200;
            this.txtUrunMevcutStokMiktari.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUrunMevcutStokMiktari.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUrunMevcutStokMiktari.BackColor = System.Drawing.Color.Transparent;
            this.txtUrunMevcutStokMiktari.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUrunMevcutStokMiktari.BackgroundImage")));
            this.txtUrunMevcutStokMiktari.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUrunMevcutStokMiktari.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUrunMevcutStokMiktari.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUrunMevcutStokMiktari.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUrunMevcutStokMiktari.BorderRadius = 20;
            this.txtUrunMevcutStokMiktari.BorderThickness = 1;
            this.txtUrunMevcutStokMiktari.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUrunMevcutStokMiktari.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunMevcutStokMiktari.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtUrunMevcutStokMiktari.DefaultText = "";
            this.txtUrunMevcutStokMiktari.FillColor = System.Drawing.Color.White;
            this.txtUrunMevcutStokMiktari.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtUrunMevcutStokMiktari.HideSelection = true;
            this.txtUrunMevcutStokMiktari.IconLeft = null;
            this.txtUrunMevcutStokMiktari.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunMevcutStokMiktari.IconPadding = 10;
            this.txtUrunMevcutStokMiktari.IconRight = null;
            this.txtUrunMevcutStokMiktari.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunMevcutStokMiktari.Lines = new string[0];
            this.txtUrunMevcutStokMiktari.Location = new System.Drawing.Point(172, 264);
            this.txtUrunMevcutStokMiktari.MaxLength = 32767;
            this.txtUrunMevcutStokMiktari.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUrunMevcutStokMiktari.Modified = false;
            this.txtUrunMevcutStokMiktari.Multiline = false;
            this.txtUrunMevcutStokMiktari.Name = "txtUrunMevcutStokMiktari";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunMevcutStokMiktari.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUrunMevcutStokMiktari.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunMevcutStokMiktari.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunMevcutStokMiktari.OnIdleState = stateProperties24;
            this.txtUrunMevcutStokMiktari.Padding = new System.Windows.Forms.Padding(3);
            this.txtUrunMevcutStokMiktari.PasswordChar = '\0';
            this.txtUrunMevcutStokMiktari.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtUrunMevcutStokMiktari.PlaceholderText = "Ürünün Mevcut Olan Stok Miktarı";
            this.txtUrunMevcutStokMiktari.ReadOnly = false;
            this.txtUrunMevcutStokMiktari.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUrunMevcutStokMiktari.SelectedText = "";
            this.txtUrunMevcutStokMiktari.SelectionLength = 0;
            this.txtUrunMevcutStokMiktari.SelectionStart = 0;
            this.txtUrunMevcutStokMiktari.ShortcutsEnabled = true;
            this.txtUrunMevcutStokMiktari.Size = new System.Drawing.Size(260, 37);
            this.txtUrunMevcutStokMiktari.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUrunMevcutStokMiktari.TabIndex = 12;
            this.txtUrunMevcutStokMiktari.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUrunMevcutStokMiktari.TextMarginBottom = 0;
            this.txtUrunMevcutStokMiktari.TextMarginLeft = 3;
            this.txtUrunMevcutStokMiktari.TextMarginTop = 0;
            this.txtUrunMevcutStokMiktari.TextPlaceholder = "Ürünün Mevcut Olan Stok Miktarı";
            this.txtUrunMevcutStokMiktari.UseSystemPasswordChar = false;
            this.txtUrunMevcutStokMiktari.WordWrap = true;
            this.txtUrunMevcutStokMiktari.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtUrunMevcutStokMiktari_KeyPress);
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Calibri", 12F);
            this.bunifuLabel6.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel6.Location = new System.Drawing.Point(507, 276);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(85, 19);
            this.bunifuLabel6.TabIndex = 5;
            this.bunifuLabel6.Text = "Ürün Ağırlığı:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtUrunBarkodSeriNo
            // 
            this.txtUrunBarkodSeriNo.AcceptsReturn = false;
            this.txtUrunBarkodSeriNo.AcceptsTab = false;
            this.txtUrunBarkodSeriNo.AnimationSpeed = 200;
            this.txtUrunBarkodSeriNo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUrunBarkodSeriNo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUrunBarkodSeriNo.BackColor = System.Drawing.Color.Transparent;
            this.txtUrunBarkodSeriNo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUrunBarkodSeriNo.BackgroundImage")));
            this.txtUrunBarkodSeriNo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUrunBarkodSeriNo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUrunBarkodSeriNo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUrunBarkodSeriNo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUrunBarkodSeriNo.BorderRadius = 20;
            this.txtUrunBarkodSeriNo.BorderThickness = 1;
            this.txtUrunBarkodSeriNo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUrunBarkodSeriNo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunBarkodSeriNo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtUrunBarkodSeriNo.DefaultText = "";
            this.txtUrunBarkodSeriNo.FillColor = System.Drawing.Color.White;
            this.txtUrunBarkodSeriNo.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtUrunBarkodSeriNo.HideSelection = true;
            this.txtUrunBarkodSeriNo.IconLeft = null;
            this.txtUrunBarkodSeriNo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunBarkodSeriNo.IconPadding = 10;
            this.txtUrunBarkodSeriNo.IconRight = null;
            this.txtUrunBarkodSeriNo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunBarkodSeriNo.Lines = new string[0];
            this.txtUrunBarkodSeriNo.Location = new System.Drawing.Point(197, 156);
            this.txtUrunBarkodSeriNo.MaxLength = 32767;
            this.txtUrunBarkodSeriNo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUrunBarkodSeriNo.Modified = false;
            this.txtUrunBarkodSeriNo.Multiline = false;
            this.txtUrunBarkodSeriNo.Name = "txtUrunBarkodSeriNo";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunBarkodSeriNo.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUrunBarkodSeriNo.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunBarkodSeriNo.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunBarkodSeriNo.OnIdleState = stateProperties28;
            this.txtUrunBarkodSeriNo.Padding = new System.Windows.Forms.Padding(3);
            this.txtUrunBarkodSeriNo.PasswordChar = '\0';
            this.txtUrunBarkodSeriNo.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtUrunBarkodSeriNo.PlaceholderText = "Seri Numara veya Barkod No";
            this.txtUrunBarkodSeriNo.ReadOnly = false;
            this.txtUrunBarkodSeriNo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUrunBarkodSeriNo.SelectedText = "";
            this.txtUrunBarkodSeriNo.SelectionLength = 0;
            this.txtUrunBarkodSeriNo.SelectionStart = 0;
            this.txtUrunBarkodSeriNo.ShortcutsEnabled = true;
            this.txtUrunBarkodSeriNo.Size = new System.Drawing.Size(260, 37);
            this.txtUrunBarkodSeriNo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUrunBarkodSeriNo.TabIndex = 10;
            this.txtUrunBarkodSeriNo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUrunBarkodSeriNo.TextMarginBottom = 0;
            this.txtUrunBarkodSeriNo.TextMarginLeft = 3;
            this.txtUrunBarkodSeriNo.TextMarginTop = 0;
            this.txtUrunBarkodSeriNo.TextPlaceholder = "Seri Numara veya Barkod No";
            this.txtUrunBarkodSeriNo.UseSystemPasswordChar = false;
            this.txtUrunBarkodSeriNo.WordWrap = true;
            this.txtUrunBarkodSeriNo.TextChanged += new System.EventHandler(this.txtUrunBarkodSeriNo_TextChanged);
            this.txtUrunBarkodSeriNo.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtUrunBarkodSeriNo_KeyPress);
            // 
            // txtUrunKategorisi
            // 
            this.txtUrunKategorisi.AcceptsReturn = false;
            this.txtUrunKategorisi.AcceptsTab = false;
            this.txtUrunKategorisi.AnimationSpeed = 200;
            this.txtUrunKategorisi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUrunKategorisi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUrunKategorisi.BackColor = System.Drawing.Color.Transparent;
            this.txtUrunKategorisi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUrunKategorisi.BackgroundImage")));
            this.txtUrunKategorisi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUrunKategorisi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUrunKategorisi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUrunKategorisi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUrunKategorisi.BorderRadius = 20;
            this.txtUrunKategorisi.BorderThickness = 1;
            this.txtUrunKategorisi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUrunKategorisi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunKategorisi.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtUrunKategorisi.DefaultText = "";
            this.txtUrunKategorisi.FillColor = System.Drawing.Color.White;
            this.txtUrunKategorisi.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.txtUrunKategorisi.HideSelection = true;
            this.txtUrunKategorisi.IconLeft = null;
            this.txtUrunKategorisi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunKategorisi.IconPadding = 10;
            this.txtUrunKategorisi.IconRight = null;
            this.txtUrunKategorisi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUrunKategorisi.Lines = new string[0];
            this.txtUrunKategorisi.Location = new System.Drawing.Point(636, 156);
            this.txtUrunKategorisi.MaxLength = 32767;
            this.txtUrunKategorisi.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUrunKategorisi.Modified = false;
            this.txtUrunKategorisi.Multiline = false;
            this.txtUrunKategorisi.Name = "txtUrunKategorisi";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunKategorisi.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUrunKategorisi.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunKategorisi.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUrunKategorisi.OnIdleState = stateProperties32;
            this.txtUrunKategorisi.Padding = new System.Windows.Forms.Padding(3);
            this.txtUrunKategorisi.PasswordChar = '\0';
            this.txtUrunKategorisi.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtUrunKategorisi.PlaceholderText = "Ürüne Ait Kategori";
            this.txtUrunKategorisi.ReadOnly = false;
            this.txtUrunKategorisi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUrunKategorisi.SelectedText = "";
            this.txtUrunKategorisi.SelectionLength = 0;
            this.txtUrunKategorisi.SelectionStart = 0;
            this.txtUrunKategorisi.ShortcutsEnabled = true;
            this.txtUrunKategorisi.Size = new System.Drawing.Size(260, 37);
            this.txtUrunKategorisi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUrunKategorisi.TabIndex = 11;
            this.txtUrunKategorisi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUrunKategorisi.TextMarginBottom = 0;
            this.txtUrunKategorisi.TextMarginLeft = 3;
            this.txtUrunKategorisi.TextMarginTop = 0;
            this.txtUrunKategorisi.TextPlaceholder = "Ürüne Ait Kategori";
            this.txtUrunKategorisi.UseSystemPasswordChar = false;
            this.txtUrunKategorisi.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Calibri", 12F);
            this.bunifuLabel3.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel3.Location = new System.Drawing.Point(24, 165);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(150, 19);
            this.bunifuLabel3.TabIndex = 2;
            this.bunifuLabel3.Text = "Ürün Barkod Numarası:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Calibri", 12F);
            this.bunifuLabel5.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel5.Location = new System.Drawing.Point(22, 271);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(116, 19);
            this.bunifuLabel5.TabIndex = 4;
            this.bunifuLabel5.Text = "Ürün Stok Miktarı:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Calibri", 12F);
            this.bunifuLabel4.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel4.Location = new System.Drawing.Point(498, 167);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(104, 19);
            this.bunifuLabel4.TabIndex = 3;
            this.bunifuLabel4.Text = "Ürün Kategorisi:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // UrunEkle
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(33)))), ((int)(((byte)(74)))));
            this.ClientSize = new System.Drawing.Size(1139, 619);
            this.Controls.Add(this.bunifuGroupBox2);
            this.Controls.Add(this.exit);
            this.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "UrunEkle";
            this.Load += new System.EventHandler(this.UrunEkle_Load);
            this.bunifuGroupBox2.ResumeLayout(false);
            this.bunifuGroupBox2.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label exit;
        private Bunifu.UI.WinForms.BunifuTextBox txtUrunAdı;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox txtUrunBarkodSeriNo;
        private Bunifu.UI.WinForms.BunifuTextBox txtUrunKategorisi;
        private Bunifu.UI.WinForms.BunifuTextBox txtUrunMevcutStokMiktari;
        private Bunifu.UI.WinForms.BunifuTextBox txtUrunAgırlıgı;
        private Bunifu.UI.WinForms.BunifuTextBox txtUrunBırımFıyatı;
        private Bunifu.UI.WinForms.BunifuTextBox txtUrunTedarikcisi;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox txtUrunID;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
    }
}